### ISSUE TITLE
Build fails with JDK 16

### ISSUE THREAD

**Issue by msgilligan** [micronaut-projects/micronaut-acme#151]
The build fails with JDK 16. Upgrading to Gradle 7.1 (and possibly additional work) is necessary.

### Steps to Reproduce

1. `sdk use java 16.0.1.hs-adpt`
2. `./gradlew clean build`

### Expected Behaviour

Build should complete successfully

### Actual Behaviour

```
$ java -version
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)
[sean@MSG-MBPro-Touch-Bar:103]$ ./gradlew clean build

> Task :acme:compileJava FAILED
Note: Creating bean classes for 7 type elements
Note: /Users/sean/git/micronaut-acme/acme/src/main/java/io/micronaut/acme/ssl/DelegatedSslContext.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':acme:compileJava'.
> java.lang.IllegalAccessError: class org.gradle.internal.compiler.java.ClassNameCollector (in unnamed module @0x6040ecec) cannot access class com.sun.tools.javac.code.Symbol$TypeSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x6040ecec

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
5 actionable tasks: 5 executed
```
### Environment Information

- **Operating System**: macOS Big Sur 11.3.1
- **Micronaut Version:** 2.1.4 (Current `master` branch of `micronaut-acme` fc6bbc9b08b31ab63737aee4321d7d89a7c5c4c4)
- **JDK Version:** AdoptOpenJDK-16.0.1+9

### Example Application

Not applicable.

**Comment by msgilligan** [comment]
To get JDK 16 build to work:

1. PR #152 
2. Update a handful of dependencies (see other PRs)
3. Comment out `plugin: "io.micronaut.build.internal.dependency-updates"`

I upgraded:
```
micronautVersion=2.5.6
groovyVersion=3.0.8
spockVersion=2.0-groovy-3.0
acmeVersion=2.11
objenesisVersion=3.2
```

**Comment by ilopmar** [comment]
The `acmeVersion` upgrade shouldn't target Micronaut 2.5.x patch release. Probably all these changes you are doing should be done directly for Micronaut 3 release (#148)

**Comment by msgilligan** [comment]
> The `acmeVersion` upgrade shouldn't target Micronaut 2.5.x patch release.

I'm just curious, is there a (technical) reason for this other than the Micronaut team wants to focus efforts on the Micronaut 3 release?

> Probably all these changes you are doing should be done directly for Micronaut 3 release (#148)

Sure. Sounds like that will be more in alignment with what the core team is doing. (I guess that means I better test my apps out with Micronaut 3.0-M2...)

Will this work be done on `master`?

**Comment by ilopmar** [comment]
> > The `acmeVersion` upgrade shouldn't target Micronaut 2.5.x patch release.
> 
> I'm just curious, is there a (technical) reason for this other than the Micronaut team wants to focus efforts on the Micronaut 3 release?

Basically we don't upgrade 3rd party minor dependencies in Micronaut patch versions because we don't want to break users' applications. See https://github.com/micronaut-projects/micronaut-core/wiki/Module-Upgrade-Strategy. Of course there can be exceptions to that rule (an maybe this is one of those)

Another approach if you really need acme upgraded is that we can release a new version targeting 2.5.x but that version won't be included in the bom automatically, so you need to set the version manually. 


> > Probably all these changes you are doing should be done directly for Micronaut 3 release (#148)
> 
> Sure. Sounds like that will be more in alignment with what the core team is doing. (I guess that means I better test my apps out with Micronaut 3.0-M2...)
> 
> Will this work be done on `master`?

Yes, we will do all that work in master and we'll create a new branch for the previous version. But as I said, we can do another release for 2.5.x if you need it, so that will be first in master and we'll switch branches.

**Comment by msgilligan** [comment]
I am trying to release an app using Micronaut 2.5.x and I have been using a `dockerBuildNative` container successfully until I tried to add `micronaut-acme`.  (See Issue #154 which reproduces the issue with a freshly-generated Micronaut Launch project)

So maybe another release for 2.5.x might be a good idea.
