### ISSUE TITLE
Migrate the build to the new Gradle plugins

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-acme#16]

**Comment by graemerocher** [comment]
I attempted this, but not sure if the `acmi-cli` publishing setup is correct. Currently a warning is printed:

```
Multiple publications with coordinates 'io.micronaut.acme:micronaut-acme-cli:1.0.0.RC2' are published to repository 'mavenLocal'. The publications will overwrite each other!
```

And duplicate POMs exist. 

@zendern could you take a look?

**Comment by zendern** [comment]
> I attempted this, but not sure if the `acmi-cli` publishing setup is correct. Currently a warning is printed:
> 
> 
> 
> ```
> 
> Multiple publications with coordinates 'io.micronaut.acme:micronaut-acme-cli:1.0.0.RC2' are published to repository 'mavenLocal'. The publications will overwrite each other!
> 
> ```
> 
> 
> 
> And duplicate POMs exist. 
> 
> 
> 
> @zendern could you take a look

Yeah I can try to take a look this morning. Honestly the fix is to just delete the cli directory and any gradle associated with it since we are moving it all to micronaut-starter.

**Comment by graemerocher** [comment]
Great, if you can take a look maybe another RC can be issued

**Comment by zendern** [comment]
I took at stab at it.....something is broken in the example project with the shadow plugin. Its complaining about not having `mainClassName` defined and its there..... i started to look at `micronaut-graphql` since it is setup in a similar way to this project as far as examples go and from what i can tell its broken as well with the same issue. 

I have to pause this for now @graemerocher but will see what I can do this week.

**Comment by graemerocher** [comment]
Try move https://github.com/micronaut-projects/micronaut-acme/blob/master/examples/examples.gradle#L32 to before the `apply` for shadow plugin

**Comment by zendern** [comment]
> Try move https://github.com/micronaut-projects/micronaut-acme/blob/master/examples/examples.gradle#L32 to before the `apply` for shadow plugin

Ok i figured it out..... so when we switched over to all the new common gradle plugins we were now pulling in a super old version of shadow jar plugin. 

Added this task
```
task buildScriptDependencies(type: org.gradle.api.tasks.diagnostics.DependencyReportTask) {
    configurations = project.buildscript.configurations
}
```

And saw this was the version of the shadow plugin we had 2.0.2. Latest is 5.2.0
![image](https://user-images.githubusercontent.com/1099906/84688658-b1c2f100-af0d-11ea-89ce-ed2a1c9ac1d3.png)

Fixed it for now in this commit (b0eb37c420954ddc66216ed30c2726d9f93f3f0f) by setting the newest version. But Im wondering if we should have this set upstream or maybe the docs plugin shouldn't have it set as compile time?? 

Build is now passing here, going to try to cut a release next. 
https://github.com/micronaut-projects/micronaut-acme/runs/773628067

**Comment by zendern** [comment]
That looks to have done it. Release build ran and so did Maven Central Sync. I do see this in the Maven Central Sync job but it says it succeeded so it might be fine. 

![image](https://user-images.githubusercontent.com/1099906/84690545-a58c6300-af10-11ea-8ef7-a64b53b68da1.png)

https://github.com/micronaut-projects/micronaut-acme/runs/773693793?check_suite_focus=true

**Comment by zendern** [comment]
> That looks to have done it. Release build ran and so did Maven Central Sync. I do see this in the Maven Central Sync job but it says it succeeded so it might be fine.
> 
> ![image](https://user-images.githubusercontent.com/1099906/84690545-a58c6300-af10-11ea-8ef7-a64b53b68da1.png)
> 
> https://github.com/micronaut-projects/micronaut-acme/runs/773693793?check_suite_focus=true
> 

This appears to be good to go. We have 1.0.0.RC out in maven central so this 404 error means nothing. I guess it does say it retried ¯\_(ツ)_/¯ 

https://search.maven.org/search?q=g:%22io.micronaut.acme%22%20AND%20a:%22micronaut-acme%22

> Although digging through the Release job i see an update bom and it looks like it no-op'd??
> ![image](https://user-images.githubusercontent.com/1099906/84690824-20557e00-af11-11ea-84fa-01c14432a0b9.png)
> 
> https://github.com/micronaut-projects/micronaut-acme/runs/773693784?check_suite_focus=true
> 
> Is there something else that needs configured here @graemerocher ??
 
So then this is still maybe an issue. Maybe it has to be manually added like the original PR i had here that got reverted. Before the micronaut-build "bot" can do its things. 
https://github.com/micronaut-projects/micronaut-core/pull/3497

**Comment by graemerocher** [comment]
@zendern as per https://github.com/micronaut-projects/micronaut-core/pull/3497#issuecomment-643936174 I had to revert the change which is why the update BOM thing is no-op atm, if you send another PR with the version in it we can apply it
