### ISSUE TITLE
[2.0.1.snapshot]download fails

### ISSUE THREAD

**Issue by d5269357812** [micronaut-projects/micronaut-acme#83]
### Steps to Reproduce
in doc configure step

1. copy frrom doc ```implementation("io.micronaut.acme:micronaut-acme:2.0.1.BUILD-SNAPSHOT")```
2. past to build gradle
3. build gradle

### Actual Behaviour

fail to download
```
Could not find io.micronaut.acme:micronaut-acme:2.0.1.BUILD-SNAPSHOT.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/io/micronaut/acme/micronaut-acme/2.0.1.BUILD-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/io/micronaut/acme/micronaut-acme/2.0.1.BUILD-SNAPSHOT/micronaut-acme-2.0.1.BUILD-SNAPSHOT.pom
       - https://jcenter.bintray.com/io/micronaut/acme/micronaut-acme/2.0.1.BUILD-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/io/micronaut/acme/micronaut-acme/2.0.1.BUILD-SNAPSHOT/micronaut-acme-2.0.1.BUILD-SNAPSHOT.pom
     Required by:
         project : > io.micronaut:micronaut-bom:2.0.1
```

### Environment Information

- **Operating System**: macOS mojave
- **Micronaut Version:** 2.0.1
- **JDK Version:** 1.8

### Example Application

any
- TODO: link to github repository with example that reproduces the issue

**Comment by ilopmar** [comment]
You are trying to use a snapshot version with included the snapshot repository: https://docs.micronaut.io/latest/guide/index.html#usingsnapshots

Try that or use version 2.0.0 instead: https://micronaut-projects.github.io/micronaut-acme/latest/guide/index.html
